export enum AppEventTypesEnum {
  FORESIGHT = "Форсайт",
  CONFERENCE = "Конференция",
  ROUND_TABLE = "Круглый стол",
  SURVEY = "Опрос",
  MASTERCLASS = "Мастер-класс",
  WORKSHOP = "Воркшоп",
  LECTURE = "Лекция",
  FORUM = "Форум",
  MEETUP = "Митап",
  STRATEGIC_SESSION = "Стратегическая сессия",
  PANEL_DISCUSSION = "Панельная дискуссия",
  OPEN_DAY = "День открытых дверей",
  EXHIBITION = "Выставка",
  COMPETITION = "Соревнование",
  MEETING = "Встреча",
  SEMINAR = "Семинар",
  DEMO_DAY = "Демо-день",
  ACCELERATOR = "Акселератор",
  PITCH = "Питч",
  HACKATHON = "Хакатон",
}
